//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mace.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mace.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to angel
        ///bone
        ///claw
        ///dagger
        ///fall
        ///ford
        ///forge
        ///fort
        ///furnace
        ///hammer
        ///henge
        ///hold
        ///moon
        ///pass
        ///shield
        ///shire
        ///skull
        ///stone
        ///vale
        ///vine
        ///water
        ///willow
        ///winter
        ///spring
        ///summer
        /// Spring
        /// Summer
        /// Winter
        /// Fall
        /// Reach
        /// Ranch
        /// Pass
        ///ton
        ///field
        ///ville
        /// Valley
        /// Hill
        /// Nights
        /// Casino
        /// Carnival
        /// Mountain
        ///view
        /// View
        /// Village
        ///lake
        /// Lake
        /// Ocean
        /// Pond
        ///town
        /// Town
        /// Villa
        /// Polis
        ///leaf
        /// Leaf
        ///sand
        /// Sands
        ///Guild
        ///loo
        ///gate
        /// Gate
        /// Paradise
        ///&apos;s Roost
        /// Knob
        /// Knoll
        /// Plains
        /// Savannah
        /// Tundra
        /// Taiga
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CityEndingWords {
            get {
                return ResourceManager.GetString("CityEndingWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black
        ///Broken
        ///Cold
        ///Dark
        ///Death
        ///Deep
        ///Diamond
        ///Dragon
        ///Eagle
        ///Forgotten
        ///Frozen
        ///Gold
        ///Holy
        ///Iron
        ///Lost
        ///Never
        ///North
        ///Obsidian
        ///Owl
        ///Ox
        ///Raven
        ///Red
        ///Sacred
        ///Scum
        ///Shadow
        ///Silver
        ///Soul
        ///Steel
        ///Troll
        ///White
        ///Wolf
        ///New
        ///Las
        ///Los
        ///Great
        ///Fort
        ///Dog
        ///Cat
        ///Creep
        ///Creeper
        ///Zombie
        ///Pig
        ///Piglet
        ///Cow
        ///Calf
        ///Bull
        ///Sheep
        ///Ram
        ///Lamb
        ///Chicken
        ///Chick
        ///Hill
        ///Red
        ///Orange
        ///Yellow
        ///Green
        ///Blue
        ///Indigo
        ///Violet
        ///Purple
        ///Majestic
        ///Water
        ///Lake
        ///Ocean
        ///Wave
        ///Aquatic
        ///Metropolis
        ///Plain
        ///Bro
        ///Valley
        ///Mountain
        ///Mount
        ///Warrior
        ///Figh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CityStartingWords {
            get {
                return ResourceManager.GetString("CityStartingWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotNetZip (Ionic.Zlib.dll):
        ///
        ///Copyright (c) 2000,2001,2002,2003 ymnk, JCraft,Inc. All rights reserved.
        ///
        ///Redistribution and use in source and binary forms, with or without
        ///modification, are permitted provided that the following conditions are met:
        ///
        ///  1. Redistributions of source code must retain the above copyright notice,
        ///     this list of conditions and the following disclaimer.
        ///
        ///  2. Redistributions in binary form must reproduce the above copyright 
        ///     notice, this list of conditions and the f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License_DotNetZip {
            get {
                return ResourceManager.GetString("License_DotNetZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                     GNU GENERAL PUBLIC LICENSE
        ///                       Version 3, 29 June 2007
        ///
        /// Copyright (C) 2007 Free Software Foundation, Inc. &lt;http://fsf.org/&gt;
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///                            Preamble
        ///
        ///  The GNU General Public License is a free, copyleft license for
        ///software and other kinds of works.
        ///
        ///  The licenses for most software and other practical works are designed
        ///to [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License_Mace {
            get {
                return ResourceManager.GetString("License_Mace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Page: https://code.google.com/p/substrate-minecraft/
        ///
        ///Substrate Project (Substrate.dll):
        ///
        ///Copyright (C) 2011 by Justin Aquadro
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the So [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License_Substrate {
            get {
                return ResourceManager.GetString("License_Substrate", resourceCulture);
            }
        }
    }
}
